"""Add brief inline comments to notebook code cells."""
import json
from copy import deepcopy

NOTEBOOKS = ["50091136.ipynb"]

# cell_index -> list of source lines (with trailing newlines)
PATCHES: dict[int, list[str]] = {
    6: [
        "# --- Paths & reproducibility ---\n",
        'DATA_PATH = "games.csv"\n',
        "RANDOM_STATE = 42\n",
        "\n",
        "\n",
        "def dataframe_checkpoint(frame: pd.DataFrame) -> pd.DataFrame:\n",
        '    """Return an independent copy for safe downstream transforms."""\n',
        "    return frame.copy()\n",
        "\n",
        "\n",
        "def missingness_summary(frame: pd.DataFrame) -> pd.DataFrame:\n",
        '    """Missing count and percentage for columns with at least one NA."""\n',
        "    n = len(frame)\n",
        "    miss = frame.isna().sum()  # per-column NA count\n",
        '    out = pd.DataFrame({"missing": miss, "pct": (miss / n) * 100.0})\n',
        "    return out.loc[miss > 0].sort_values(\"missing\", ascending=False)\n",
        "\n",
        "\n",
        "def rotate_x_labels_if_needed(\n",
        "    ax,\n",
        "    *,\n",
        "    angle: float = 45.0,\n",
        '    ha: str = "right",\n',
        "    max_label_chars: int = 10,\n",
        "    min_tick_count: int = 8,\n",
        ") -> None:\n",
        '    """Rotate x tick labels clockwise only when labels are long or numerous."""\n',
        "    labels = [t.get_text() for t in ax.get_xticklabels() if t.get_text()]\n",
        "    if not labels:\n",
        "        return\n",
        "    # rotate only when crowded\n",
        "    if max((len(s) for s in labels), default=0) > max_label_chars or len(labels) >= min_tick_count:\n",
        "        plt.setp(ax.get_xticklabels(), rotation=angle, ha=ha)\n",
        "\n",
        "\n",
        "def rotate_x_labels(ax, angle: float = 45.0, ha: str = \"right\") -> None:\n",
        '    """Alias for rotate_x_labels_if_needed (do not force rotation on short axes)."""\n',
        "    rotate_x_labels_if_needed(ax, angle=angle, ha=ha)\n",
    ],
    8: [
        "# seaborn theme\n",
        'sns.set_theme(style="whitegrid")\n',
        "# figure defaults\n",
        "plt.rcParams.update(\n",
        "    {\n",
        '        "figure.figsize": (10, 5),\n',
        '        "figure.dpi": 120,\n',
        '        "axes.titlesize": 14,\n',
        '        "axes.labelsize": 12,\n',
        '        "xtick.labelsize": 10,\n',
        '        "ytick.labelsize": 10,\n',
        '        "legend.fontsize": 10,\n',
        "    }\n",
        ")\n",
    ],
    10: [
        "# read CSV (immutable)\n",
        'df_raw = pd.read_csv(DATA_PATH, low_memory=False, encoding="utf-8")\n',
        "# mutable working copy\n",
        "df = df_raw.copy()\n",
    ],
    13: [
        "# Section 2.1 — head, tail, middle-band sample, then shape\n",
        "from IPython.display import display\n",
        "\n",
        "n_rows = len(df)\n",
        "mid_lo = n_rows // 4  # 25% row index\n",
        "mid_hi = (3 * n_rows) // 4  # 75% row index\n",
        "\n",
        "head_five = df.head(5)\n",
        "tail_five = df.tail(5)\n",
        "middle_five = df.iloc[mid_lo:mid_hi].sample(5, random_state=RANDOM_STATE)\n",
        "\n",
        'print("【test log】 total rows:", n_rows)\n',
        'print("【test log】 middle band row-index range (iloc):", mid_lo, "to", mid_hi - 1)\n',
        'print("【test log】 middle-band size (rows):", mid_hi - mid_lo)\n',
        'print("【test log】 sampled middle row indices:", middle_five.index.tolist())\n',
        "\n",
        'print("\\n--- First five rows ---")\n',
        "display(head_five)\n",
        "\n",
        'print("\\n--- Last five rows ---")\n',
        "display(tail_five)\n",
        "\n",
        'print("\\n--- Random five rows from middle band (25%–75%) ---")\n',
        "display(middle_five)\n",
        "\n",
        'print("\\n--- Dataset shape ---")\n',
        'print("【test log】 df.shape (rows, columns)")\n',
        "print(df.shape)\n",
        "\n",
    ],
    16: [
        "# Section 2.2 — column names, pandas dtypes, within-column type consistency\n",
        "from IPython.display import display\n",
        "\n",
        "col_list = pd.Index(df.columns).tolist()\n",
        'print("【test log】 column count:", len(col_list))\n',
        "\n",
        "# pandas storage dtypes\n",
        "dtype_df = (\n",
        "    df.dtypes.astype(str)\n",
        '    .rename("pandas_dtype")\n',
        "    .reset_index()\n",
        '    .rename(columns={"index": "column"})\n',
        ")\n",
        "display(dtype_df)\n",
        "\n",
        'print("【test log】 dtype counts (pandas storage)")\n',
        "print(df.dtypes.astype(str).value_counts().to_string())\n",
        "\n",
        "# runtime Python type check\n",
        "mixed_rows = []\n",
        "for col in df.columns:\n",
        "    non_null = df[col].dropna()\n",
        "    if non_null.empty:\n",
        "        continue\n",
        "    type_counts = non_null.map(lambda x: type(x).__name__).value_counts()\n",
        "    if len(type_counts) > 1:\n",
        "        mixed_rows.append(\n",
        "            {\n",
        '                "column": col,\n',
        '                "pandas_dtype": str(df[col].dtype),\n',
        '                "runtime_types": type_counts.to_dict(),\n',
        "            }\n",
        "        )\n",
        "\n",
        'print("【test log】 columns with multiple runtime Python types:", len(mixed_rows))\n',
        "if mixed_rows:\n",
        "    display(pd.DataFrame(mixed_rows))\n",
        "else:\n",
        "    print(\n",
        '        "【test log】 none — each non-empty column has a single runtime type among non-null values"\n',
        "    )\n",
        "\n",
        "# dtype count bar chart\n",
        "dtype_counts = df.dtypes.astype(str).value_counts()\n",
        "fig, ax = plt.subplots(figsize=(7, 4))\n",
        'dtype_counts.sort_values().plot.barh(ax=ax, color="#5b8fb8")\n',
        'ax.set_title("Pandas storage dtypes (40 columns)")\n',
        'ax.set_xlabel("Number of columns")\n',
        'ax.set_ylabel("")\n',
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
    ],
    21: [
        "# Section 2.3 — numeric range (mean/median/mode/skew), text length, float precision\n",
        "from IPython.display import display\n",
        "from scipy import stats\n",
        "\n",
        "# numeric summary loop\n",
        "num_df = df.select_dtypes(include=[np.number])\n",
        "stat_rows = []\n",
        "for col in num_df.columns:\n",
        "    s = num_df[col].dropna()\n",
        "    if s.empty:\n",
        "        continue\n",
        "    mode_ser = s.mode()\n",
        "    mode_val = mode_ser.iloc[0] if len(mode_ser) else np.nan\n",
        "    stat_rows.append(\n",
        "        {\n",
        '            "column": col,\n',
        '            "min": float(s.min()),\n',
        '            "max": float(s.max()),\n',
        '            "mean": float(s.mean()),\n',
        '            "median": float(s.median()),\n',
        '            "mode": float(mode_val) if pd.notna(mode_val) else np.nan,\n',
        '            "mode_count": int((s == mode_val).sum()) if len(mode_ser) else 0,\n',
        '            "skew": float(stats.skew(s, nan_policy="omit")) if len(s) > 2 else np.nan,\n',
        "        }\n",
        "    )\n",
        'stat_df = pd.DataFrame(stat_rows).set_index("column")\n',
        'display(stat_df.sort_values("skew", ascending=False))\n',
        "\n",
        "large_num = stat_df[stat_df[\"max\"] >= 1_000_000]\n",
        'print("【test log】 numeric columns with max >= 1,000,000:", len(large_num))\n',
        "if not large_num.empty:\n",
        '    print(large_num[["max", "mean", "median", "skew"]].to_string())\n',
        "\n",
        'high_skew = stat_df[stat_df["skew"].abs() > 1.0].sort_values("skew", ascending=False)\n',
        'print("【test log】 columns with |skew| > 1.0:", len(high_skew))\n',
        "\n",
        "# text column lengths\n",
        'text_cols = list(df.select_dtypes(include=["object", "string"]).columns)\n',
        "len_rows = []\n",
        "for col in text_cols:\n",
        "    ser = df[col].dropna().astype(str)\n",
        "    if ser.empty:\n",
        "        continue\n",
        "    slen = ser.str.len()\n",
        "    len_rows.append(\n",
        "        {\n",
        '            "column": col,\n',
        '            "char_len_min": int(slen.min()),\n',
        '            "char_len_mean": float(slen.mean()),\n',
        '            "char_len_max": int(slen.max()),\n',
        "        }\n",
        "    )\n",
        'len_df = pd.DataFrame(len_rows).sort_values("char_len_max", ascending=False)\n',
        "display(len_df)\n",
        "\n",
        "long_text = len_df[len_df[\"char_len_max\"] >= 10_000]\n",
        'print("【test log】 text columns with max length >= 10,000 chars:", len(long_text))\n',
        "if not long_text.empty:\n",
        "    print(long_text.to_string(index=False))\n",
        "\n",
        "# float64 precision probe\n",
        "fi = np.finfo(np.float64)\n",
        'print("【test log】 float64 machine epsilon:", fi.eps)\n',
        'print("【test log】 float64 decimal digits (approx):", fi.precision)\n',
        "\n",
        "price_frac = (\n",
        '    df["Price"]\n',
        "    .dropna()\n",
        "    .map(\n",
        '        lambda v: len(f"{float(v):f}".rstrip("0").rstrip(".").split(".")[-1])\n',
        '        if "." in f"{float(v):f}"\n',
        "        else 0\n",
        "    )\n",
        ")\n",
        'print("【test log】 Price max fractional digits seen:", int(price_frac.max()))\n',
        "\n",
    ],
    25: [
        "# Section 2.3.1a — skew comparison bar (single figure)\n",
        "from scipy import stats\n",
        "\n",
        "SKEW_FEATURES = [\n",
        '    "Average playtime forever",\n',
        '    "Peak CCU",\n',
        '    "Positive",\n',
        '    "Recommendations",\n',
        '    "Price",\n',
        "]\n",
        "\n",
        "skew_rows = []\n",
        "for col in SKEW_FEATURES:\n",
        "    ser = df[col].dropna()\n",
        "    skew_rows.append(\n",
        "        {\n",
        '            "feature": col,\n',
        '            "skew": float(stats.skew(ser)),\n',
        '            "zero_pct": float((ser == 0).mean() * 100.0),\n',
        "        }\n",
        "    )\n",
        'skew_df = pd.DataFrame(skew_rows).sort_values("skew", ascending=False)\n',
        'print("【test log】 skew comparison (selected features):")\n',
        "print(skew_df.to_string(index=False))\n",
        "\n",
        "# skew bar chart\n",
        "fig, ax = plt.subplots(figsize=(9, 5))\n",
        'sns.barplot(data=skew_df, x="feature", y="skew", hue="feature", dodge=False, legend=False, ax=ax)\n',
        'ax.set_xlabel("Feature")\n',
        'ax.set_ylabel("Pearson skewness")\n',
        'ax.set_title("Skewness comparison — selected numeric features")\n',
        "rotate_x_labels_if_needed(ax)\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
    ],
    28: [
        "# Section 2.3.1b — raw-scale boxplots (five features, single figure)\n",
        "BOX_FEATURES = [\n",
        '    "Positive",\n',
        '    "Peak CCU",\n',
        '    "Average playtime forever",\n',
        '    "Recommendations",\n',
        '    "Price",\n',
        "]\n",
        "\n",
        "q_tbl = df[BOX_FEATURES].quantile([0.25, 0.5, 0.75]).T\n",
        'q_tbl.columns = ["Q1", "median", "Q3"]\n',
        'print("【test log】 quartiles (selected features):")\n',
        "print(q_tbl.to_string())\n",
        "\n",
        'box_long = df[BOX_FEATURES].melt(var_name="feature", value_name="value")\n',
        "\n",
        "fig, ax = plt.subplots(figsize=(11, 5))\n",
        'sns.boxplot(data=box_long, x="feature", y="value", hue="feature", dodge=False, legend=False, ax=ax)\n',
        'ax.set_xlabel("")\n',
        'ax.set_ylabel("Raw value (mixed units)")\n',
        'ax.set_title("Boxplots on raw scale — five selected features")\n',
        "rotate_x_labels_if_needed(ax)\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
    ],
    31: [
        "# Section 2.3.1c — log1p boxplots (same five features, single figure)\n",
        'box_long["log_value"] = np.log1p(box_long["value"])\n',
        "\n",
        "fig, ax = plt.subplots(figsize=(11, 5))\n",
        "sns.boxplot(\n",
        "    data=box_long,\n",
        '    x="feature",\n',
        '    y="log_value",\n',
        '    hue="feature",\n',
        "    dodge=False,\n",
        "    legend=False,\n",
        "    ax=ax,\n",
        ")\n",
        'ax.set_xlabel("")\n',
        'ax.set_ylabel("log1p(value)")\n',
        'ax.set_title("Boxplots after log1p — five selected features")\n',
        "rotate_x_labels_if_needed(ax)\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
    ],
    34: [
        "# Section 2.3.1d — histogram of Positive votes (single figure)\n",
        'pos = df["Positive"].dropna()\n',
        "print(\n",
        '    "【test log】 Positive zero rows:",\n',
        "    int((pos == 0).sum()),\n",
        '    f"({(pos == 0).mean() * 100:.2f}%)",\n',
        ")\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(8, 5))\n",
        "sns.histplot(pos, bins=80, kde=True, ax=ax)\n",
        'ax.set_xlabel("Positive review count")\n',
        'ax.set_ylabel("Number of listings")\n',
        'ax.set_title("Distribution of Positive votes (raw scale)")\n',
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
    ],
    37: [
        "# Section 2.3.1e — histogram of Peak CCU (single figure)\n",
        'ccu = df["Peak CCU"].dropna()\n',
        "print(\n",
        '    "【test log】 Peak CCU zero rows:",\n',
        "    int((ccu == 0).sum()),\n",
        '    f"({(ccu == 0).mean() * 100:.2f}%)",\n',
        ")\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(8, 5))\n",
        "sns.histplot(ccu, bins=80, kde=True, ax=ax)\n",
        'ax.set_xlabel("Peak CCU (players)")\n',
        'ax.set_ylabel("Number of listings")\n',
        'ax.set_title("Distribution of Peak CCU (raw scale)")\n',
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
    ],
    40: [
        "# Section 2.3.1f — histogram of list Price (single figure)\n",
        'price = df["Price"].dropna()\n',
        "print(\n",
        '    "【test log】 Price zero rows:",\n',
        "    int((price == 0).sum()),\n",
        '    f"({(price == 0).mean() * 100:.2f}%)",\n',
        ")\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(8, 5))\n",
        "sns.histplot(price, bins=60, kde=True, ax=ax)\n",
        'ax.set_xlabel("Price (USD)")\n',
        'ax.set_ylabel("Number of listings")\n',
        'ax.set_title("Distribution of list Price (raw scale)")\n',
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
    ],
}


def apply_patches(nb_path: str) -> int:
    with open(nb_path, encoding="utf-8") as f:
        nb = json.load(f)

    applied = 0
    for idx, lines in PATCHES.items():
        if nb["cells"][idx]["cell_type"] != "code":
            raise ValueError(f"Cell {idx} is not code in {nb_path}")
        nb["cells"][idx]["source"] = lines
        applied += 1

    with open(nb_path, "w", encoding="utf-8") as f:
        json.dump(nb, f, ensure_ascii=False, indent=1)

    return applied


if __name__ == "__main__":
    for path in NOTEBOOKS:
        n = apply_patches(path)
        print(f"{path}: patched {n} cells (batch 1)")
